### ISSUE TITLE
Event name doesn't show up

### ISSUE THREAD

**Issue by gracekfan** [tamuhack-org/Ouroboros#257]
We have a variable that stores event name and we call it on pages like login, but it doesn't show up

ex. variable = tamuhack, but the text tamuhack doesn't show up anywhere

**Comment by SaltyQuetzals** [comment]
We originally handled this by providing [a custom context processor](https://docs.djangoproject.com/en/2.2/ref/templates/api/#writing-your-own-context-processors) in the [old version of Ouroboros](https://github.com/tamuhack-org/Ouroboros/blob/4c94ab46bdc7166bca9f0415100cbeec7716a82d/ouroboros/ouroboros/context_processors.py). We'll want a new file `shared/context_processors.py`

```python
# shared/context_processors.py
from django.conf import settings

def customization(request):
    return {
        "event_name": settings.EVENT_NAME,
        "event_start_date": settings.EVENT_START_DATE,
        "event_end_date": settings.EVENT_END_DATE,
    }
```

And we'll want to provide it in the base settings [similarly to how we did before](https://github.com/tamuhack-org/Ouroboros/blob/4c94ab46bdc7166bca9f0415100cbeec7716a82d/ouroboros/ouroboros/settings/base.py#L70).

The path should be `shared.context_processors.customization`, though, instead of what's in the link.
