### ISSUE TITLE
413 Request Entity Too Large error instead of invalid file extension error

### ISSUE THREAD

**Issue by cameronbrill** [tamuhack-org/Ouroboros#263]
**Describe the Bug**
Submitting a large csv (presumably a large file of any file extension) as resume leads to a 413 Request Entity Too Large error.

**To Reproduce**
1. Log in to register.tamuhack.com.
2. Begin application.
3. Fill in all required fields properly, aside from resume upload.
4. For the resume upload, submit a large file (I used a 27 MB CSV).
5. Submit application.
6. See error.

**Expected behavior**
When submitting a non-pdf file, the user should get an error saying that the only accepted file extension is pdf.

**Screenshots**
![image](https://user-images.githubusercontent.com/37822869/67626926-81accd80-f818-11e9-833e-fb172c1f7845.png)

**Additional context**
I was going through QA Test #232

**Comment by SaltyQuetzals** [comment]
Because our Django server is running behind an Nginx proxy, this error comes from Nginx, not Django itself. Here's how it works:

The [default maximum body size for Nginx is 1MB](https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size). This request is never actually hitting the Django server at all (which would error because the filetype isn't a PDF), Nginx is cancelling the request due to the body size being too large. To change this, we can change the Nginx configuration. However, a file size of 27MB is still larger than the default [`DATA_UPLOAD_MAX_MEMORY_SIZE`](https://docs.djangoproject.com/en/1.11/ref/settings/#data-upload-max-memory-size) setting. For now, we'll leave these settings alone (I hope nobody's resume is >1MB).
