### ISSUE TITLE
Application: "If you chose 'Prefer to self-describe', please elaborate" question is repeated twice and marked as required

### ISSUE THREAD

**Issue by sophialee0416** [tamuhack-org/Ouroboros#291]
**Describe the Bug**
"If you chose 'Prefer to self-describe', please elaborate" question is repeated twice on the application, before and after the race question. It's also marked as a required question, which it shouldn't be.

**Comment by SaltyQuetzals** [comment]
@jonathan-innis Just hide the fields by default, and show them only if "Prefer to self-describe" is checked using JS.

@sophialee0416 The "required" asterisk is actually a CSS trick, I think we're gonna ditch them. Since all of the fields (except for the "other") are required, the asterisks don't have any meaning.
